export const INITIATE_SAVE_OAUTH_TOKEN = "INITIATE_SAVE_OAUTH_TOKEN"
export const COMPLETE_SAVE_OAUTH_TOKEN = "COMPLETE_SAVE_OAUTH_TOKEN"
export const INITIATE_LOGOUT = "INITIATE_LOGOUT"
export const COMPLETE_LOGOUT = "COMPLETE_LOGOUT"